Tuned the scripts a bit

diff --git a/pull b/pull
--- a/pull
+++ b/pull
@@ -7,9 +7,8 @@
 # You'll need to change value of variable "svnSiqRepoPath" to set path of gateway folder relative to git hub Root folder
 
 localRepos="bake, mesh, scheme, bastion, spire, auxl, dax, daft, enamel, bedrockjs, csi, gloss, lookandfeel, siq-vendor-js"
-upstreamRepos="bastion, spire, dax, auxl, daft"
-gitHubRootFolderPath=".." 
-svnSiqRepoPath="..\siq_repo\trunk\gateway"
+#upstreamRepos="bastion, spire, dax, auxl, daft"
+svnSiqRepoPath="../svn/siq_repo/gateway"
 localUpdatedRepos=""
 upstreamUpdatedRepos=""
 
@@ -17,11 +16,30 @@ if [ $1 ]; then localRepos="$1"; fi
 if [ $2 ]; then upstreamRepos="$2"; fi
 if [ $3 ]; then svnSiqRepoPath="$3"; fi
 
-cd $gitHubRootFolderPath
-pwd
+localArr=$(echo $localRepos | tr "," "\n")
+upstreamArr=$(echo $upstreamRepos | tr "," "\n")
 
 function quit  {
-	if [ "$2" ]; then echo "Error Message: $2"; fi
+	if [ "$1" ]; then echo "Error Message: $1"; fi
+
+	for x in $localArr
+	do
+		if [ -f ~/tmppull$x.txt ]; then 
+			Echo -ne Pull result for $x:" "  
+			cat ~/tmppull$x.txt
+			rm ~/tmppull$x.txt
+		fi
+	done
+
+	for x in $upstreamArr
+	do
+		if [ -f ~/tmpfetch$x.txt ]; then 
+			Echo -ne Fetch result for $x:" "  
+			cat ~/tmpfetch$x.txt
+			rm ~/tmpfetch$x.txt
+		fi
+	done
+
 	if [ "$localUpdatedRepos" != "" ]; then
 		echo -------------Repos updated locally-------------
 		echo $localUpdatedRepos
@@ -33,67 +51,62 @@ function quit  {
 		echo $upstreamUpdatedRepos
 		echo -----------------------------------------------------------
 	fi
-	rm ~/tmp.txt
 	exit 0 
 }
 
 echo Updating Local Repos [$localRepos]
 
-arr=$(echo $localRepos | tr "," "\n")
-
-for x in $arr
-do
-	echo
-	echo Updating $x
-	cd $x
-	if [ $? -ne 0 ]; then quit 1; fi
+function pullProject {
+	cd $1
+	if [ $? -ne 0 ]; then quit; fi
 	
-	git pull > ~/tmp.txt
-	if [ $? -ne 0 ]; then
-		quit 1, "Unable to pull from $x"
+	git pull &> ~/tmppull$1.txt 
 		
-	fi
-	cat ~/tmp.txt
-	
-	grep_output="$(grep "Already up-to-date." ~/tmp.txt)"
+	grep_output="$(grep "Already up-to-date." ~/tmppull$1.txt)"
 	if [ -z "$grep_output" ]; then
-		localUpdatedRepos=${localUpdatedRepos}" ,"$x
+		localUpdatedRepos=${localUpdatedRepos}" ,"$1
 	fi
 	cd - &> /dev/null
-done
+}
 
-echo -----------------------------------------------
-echo Updating Repos from upstream [$upstreamRepos]
-
-arr=$(echo $upstreamRepos | tr "," "\n")
-
-for x in $arr
-do
+function fetchProject {
 	echo
-	echo Updating $x
-	cd $x
-	if [ $? -ne 0 ]; then quit 1; fi
+	cd $1
+	if [ $? -ne 0 ]; then quit; fi
 	
 	git fetch upstream
-	git merge upstream/master > ~/tmp.txt
-	if [ $? -ne 0 ]; then
-		quit 1,"Unable to fetch from $x"
-	fi
-	cat ~/tmp.txt	
+	git merge upstream/master &> ~/tmpfetch$1.txt
 	
-	grep_output="$(grep "Already up-to-date." ~/tmp.txt)"
+	grep_output="$(grep "Already up-to-date." ~/tmpfetch$1.txt)"
 	if [ -z "$grep_output" ]; then
-		upstreamUpdatedRepos=${upstreamUpdatedRepos}" ,""$x"
+		upstreamUpdatedRepos=${upstreamUpdatedRepos}" ,""$1"
 	fi
 
 	cd - &> /dev/null
-done
+}
 
-	echo
-	echo Updating Gateway
-	cd $svnSiqRepoPath	
-	if [ $? -ne 0 ]; then quit 1; fi
-	svn update
-	if [ $? -ne 0 ]; then
-		quit 1, "Unable to update gateway code."
-	fi
+for x in $localArr
+do
+	pullProject $x &
+done
+wait
+
+echo Updating Repos from upstream [$upstreamRepos]
+
+for x in $upstreamArr
+do
+	fetchProject $x &
+done
+wait
+
+echo
+echo Updating Gateway
+pwd
+cd $svnSiqRepoPath	
+if [ $? -ne 0 ]; then quit; fi
+svn update
+if [ $? -ne 0 ]; then
+	quit "Unable to update gateway code."
+fi
+
+quit
