Minor adjustments to the script

diff --git a/setupenv b/setupenv
--- a/setupenv
+++ b/setupenv
@@ -17,34 +17,30 @@ if [ "$1" == 'clean' ]; then
 fi
 
 gatewayHome="/d/Projects/StoredIQ/svn/siq_repo/gateway"
-projRPath="../../../git/omersaeed/"
+projRPath="../../git/omersaeed/"
  
 function setup  {
 	#Save folder context for later pop
-	dir=`pwd`
-	pushd $dir
+	pushd .
 	
 	echo working project set to "$1"
 	cd $1
 	if [ $? -ne 0 ]; then
-		echo 'Error locating DAX, ensure that you are launching from the folder where dax is cloned'
+		echo 'Error locating project, ensure that you are launching from the folder where project is cloned'
 		exit 1
 	fi
 
-	#Make the base directories if not existing
-	mkdir static/components/models/explorers/1.0 &> /dev/null
-	mkdir static/components/models/security/1.0 &> /dev/null
-	if [ "$1" == 'daft' ]; then
-		mkdir static/components/models/infosets/1.0 &> /dev/null
-	fi
-	
 	# remove node modules/ they will be setup again
+	mkdir node_modules &> /dev/null
 	cd node_modules
+	if [ $? -ne 0 ]; then exit 1; fi
 	rm -rf *
 	cd -
 
-	#remove dax static components
+	#remove static components
+	mkdir static/components &> /dev/null
 	cd static/components
+	if [ $? -ne 0 ]; then exit 1; fi
 	mv models ..
 	rm -rf *
 	mv ../models .
@@ -52,23 +48,25 @@ function setup  {
 
 	# Setup gateway
 	cd $gatewayHome
-	if [ $? -ne 0 ]; then
-		echo 'Error locating Gateway Home, ensure that the variable is set up properly'
-		exit 1
-	fi
+	if [ $? -ne 0 ]; then exit 1; fi
 	
 	echo Baking bindings for /static/components/models/explorers/1.0
+	mkdir static/components/models/explorers/1.0 &> /dev/null
 	bake -m mesh.tasks mesh.javascript bundle=local.gateway.api.bundles.EXPLORERS_API version=[1,0] path=$projRPath$1"/static/components/models/explorers/1.0"
 	cd -
 
 	cd ../bastion
+	if [ $? -ne 0 ]; then exit 1; fi
+	mkdir static/components/models/security/1.0 &> /dev/null
 	echo Baking bindings for /static/components/models/security/1.0
 	bake -m mesh.tasks mesh.javascript bundle=bastion.security.bundle version=[1,0] path="../"$1"/static/components/models/security/1.0"
 	cd -
 	
 	if [ "$1" == 'daft' ]; then
 		cd ../enamel
+		if [ $? -ne 0 ]; then exit 1; fi
 		echo Baking bindings for /static/components/models/infosets/1.0
+		mkdir static/components/models/infosets/1.0 &> /dev/null
 		bake -m mesh.tasks mesh.javascript bundle=enamel.component.API version=[1,0] path="../"$1"/static/components/models/infosets/1.0"
 		cd -
 	fi
